services:
  visidiff:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    volumes:
      - runs:/app/.output/public/runs
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  runs:
