export default {
  original: "https://www.automester.dk/*",
  updated: "https://dev-automester.euwest01.umbraco.io/*",
  viewports: [1440, 390],
  maxDepth: 3,
  maxPages: 200,
  exclude: [],
  blockedRequestUrls: [],
  samplesPerGroup: 2,
  samplingThreshold: 5,
  fullPageMaxHeight: 10000,
  concurrency: 4,
  requestDelayMs: 0,
  retries: 2,
  ignoreRobots: false,
  threshold: 0.1,
  mask: [],
  originalAuth: {},
  updatedAuth: {},
  beforeScreenshot: undefined,
  runId: undefined,
};
